# Generated by Django 3.1.4 on 2020-12-16 19:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Goal name')),
                ('match_count', models.IntegerField(default=1, verbose_name='Match')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Salary')),
                ('term', models.IntegerField(default=12, verbose_name='Contract in month')),
                ('start', models.DateField(default=datetime.date.today, verbose_name='Contract start')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Cup name')),
                ('description', models.TextField(max_length=100, verbose_name='Cup description')),
                ('premium', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Premium')),
            ],
            options={
                'verbose_name': 'Cup',
                'verbose_name_plural': 'Cups',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Personnel category name')),
                ('description', models.TextField(max_length=100, verbose_name='Cup description')),
            ],
            options={
                'verbose_name': 'Personnel category',
                'verbose_name_plural': 'Personnel categories',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PlayerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Player category name')),
                ('description', models.TextField(max_length=100, verbose_name='Cup description')),
            ],
            options={
                'verbose_name': 'Player category',
                'verbose_name_plural': 'Player categories',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField(max_length=100, verbose_name='Cup description')),
                ('experience', models.FloatField(default=1, verbose_name='Experience in years')),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Title name')),
                ('description', models.TextField(max_length=100, verbose_name='Title description')),
                ('premium', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Premium')),
            ],
            options={
                'verbose_name': 'Title',
                'verbose_name_plural': 'Titles',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle name')),
                ('country', models.CharField(max_length=100, verbose_name='Country name')),
                ('age', models.IntegerField(default=16, verbose_name='Player age')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+375333215378', max_length=128, region=None, unique=True, verbose_name='Telephone number')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Image')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informationsystem.achievement')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informationsystem.contract')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informationsystem.playercategory')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informationsystem.qualification')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Middle name')),
                ('email', models.EmailField(default='someworkmail@gmail.com', max_length=80, unique=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+375333215378', max_length=128, region=None, unique=True, verbose_name='Telephone number')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informationsystem.contract')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informationsystem.personnelcategory')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informationsystem.qualification')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='achievement',
            name='cup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informationsystem.cup'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informationsystem.title'),
        ),
    ]
